### ISSUE TITLE
ping -R does not work from Fedora 20 for all hosts

### ISSUE THREAD

**Issue by willr3** [akara/faban#75]
I have a local test environment with multiple agents but the master is unable to reach the agents because of the use of ping -R in [harness/bin/Linux/interface:20](https://github.com/akara/faban/blob/master/harness/bin/Linux/interface#L20)
changing 

```
INTERFACE=`ping -R -c1 "${TARGET}" | grep RR | awk '{ print $2 }' 2>/tmp/interface.$$.err`
```

to use ping

```
INTERFACE=`ping -c1 "${TARGET}" | grep PING | cut -d "(" -f2 | cut -d ")" -f1 2>/tmp/interface.$$.err`
```

works in my local environment and was initially discussed in the google-group [Cannot contact hostx](https://groups.google.com/forum/#!searchin/faban-users/Cannot$20contact$20hostx/faban-users/YL2RAJHuAWE/1gCbovy-CCgJ)

**Comment by whitingjr** [comment]
Looks like this commit has broken lookups of the interface for users. Eg #121 
 Have also seen this as well in a new environment.
This commit needs to be reverted.

**Comment by willr3** [comment]
I'm seeing the same situation. The previous method (`ping -R`) works on Fedora 32 and RHEL 8 but the current method does not. I think this was actually my error back in 2014 and I'm not sure how it worked with remote agents.
