### ISSUE TITLE
Faban exits with Master terminated with exit value 143, after 10 minutes

### ISSUE THREAD

**Issue by takebach** [akara/faban#89]
With newer Java Versions, Faban is exiting after 10 minutes with the message in the log:
  Master terminated with exit value 143

Oracle Java versions higher than 8u60 run into this error.  The issue is that CmdAgentImpl implements the Unreferenced interface. So when no one has a remote reference to the CmdAgent any longer it cleans everything up, i.e. the master and the started driver agents. In order for the CmdAgentImpl to have a reference to itself, it seems that someone needs to be using the CmdService from what I can tell which gets a reference to the CmdAgent. I don't see anyone outside of the CmdAgent in the AgentBootstrap process itself that is using it. Should the Master and/or the driver agents have a reference to the CmdAgent. The Javadoc indicates that the benchmark itself should not need to have a reference to the CmdAgent, that Faban should be taking care of it for you.

So what happens is that after a set time (10 minutes default) when a garbage collection kicks off the Unreferenced interface method gets invoked and that kicks off the killing of the Master and Driver processes. To work around this we have set that timeout to a higher number so that it never invokes the Unreferenced code as part of the run. The property we set was -Djava.rmi.dgc.leaseValue=144000000 in the agent and agent.cmd script files in the jEnterprise/faban/harness/faban/bin directory.

Apparently, the cleanup mechanism was not really working in versions of Java 8u60 and lower, so the problem was not hit then.

**Comment by whitingjr** [comment]
I found setting the java.rmi.dgc.leaseValue on the agents to a high value didn't stop run being killed.
 Only commenting out this [line](https://github.com/akara/faban/blob/master/harness/src/com/sun/faban/harness/agent/CmdAgentImpl.java#L469) worked for me.

**Comment by takebach** [comment]
Its actually not an option for the agents themselves but for the AgentBootstrap process.  Did you set the java.rmi.dgc.leaseValue property by changing the jEnterprise/faban/harness/faban/bin/agent file?  For example:
..
$JAVA -classpath $CLASSPATH \\
-Djava.rmi.server.RMIClassLoaderSpi=com.sun.faban.harness.agent.RMIClassLoaderProvider \\
-Dfaban.cli.command=$0 -Dfaban.home=$FABAN_HOME \\
-Djava.security.policy=$FABAN_HOME"/config/faban.policy" \\
**-Djava.rmi.dgc.leaseValue=144000000** \\
com.sun.faban.harness.agent.AgentBootstrap $* >>agent.${HOSTNAME}.log 2>&1 &

**Comment by whitingjr** [comment]
I had been setting it on the agents. Thanks for the details to set it on the AgentBootstrap.
